include: package:flutter_lints/flutter.yaml
# riverpod lint
# analyzer:
#   plugins:
#     - custom_lint
#   errors:
#     invalid_annotation_target: ignore
#   exclude:
#     - '**/*.g.dart'
#     - '**/*.freezed.dart'
