name: edspert_fl_adv
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  # sdk
  flutter:
    sdk: flutter

  # dart
  dio: ^5.3.4
  envied: ^0.5.2
  equatable: ^2.0.5
  fetch_client: ^1.0.2
  get_it: ^7.6.4
  logger: ^2.0.2+1
  string_validator: ^1.0.2

  # flutter
  cached_network_image: ^3.3.0
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  native_dio_adapter: ^1.0.0+2
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14

  # native
  flutter_native_splash: ^2.3.6

  # annotation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.2

dev_dependencies:
  # sdk
  flutter_test:
    sdk: flutter
  
  # utils
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.1.1

  # builder
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  envied_generator: ^0.5.2
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
