name: root_lib
description: A new Flutter project.
publish_to: "none"

version: 0.4.1

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  # sdk
  flutter:
    sdk: flutter

  # dart
  dio: ^5.3.4
  envied: ^0.5.2
  equatable: ^2.0.5
  get_it: ^7.6.4
  logger: ^2.0.2+1
  string_validator: ^1.0.2

  # flutter
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14

  # firebase
  firebase_auth: ^4.15.0
  firebase_core: ^2.24.0
  google_sign_in: ^6.1.6

  # annotation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  # sdk
  flutter_test:
    sdk: flutter

  # utils
  flutter_lints: ^3.0.1

  # builder
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  envied_generator: ^0.5.2
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
