name: edspert_fl_adv
description: A new Flutter project.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.0.0
  flutter: ^3.10.0

dependencies:
  # sdk
  flutter:
    sdk: flutter

  # dart
  dio: ^5.3.4
  envied: ^0.5.2
  get_it: ^7.6.4

  # flutter
  flutter_riverpod: ^2.4.8
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2

  # native
  flutter_native_splash: ^2.3.6

  # annotation
  riverpod_annotation: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  # sdk
  flutter_test:
    sdk: flutter
  
  # utils
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.1.1

  # generator_builder
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  go_router_builder: ^2.3.4
  riverpod_generator: ^2.3.3
  envied_generator: ^0.5.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
